# 指定不需要进行风格检查的路径，Pods，脚本生成的文件
excluded: 
  - Pods
  - R.generated.swift

# 自定义某个规则（不可以修改）
force_cast: warning
line_length: 165
cyclomatic_complexity: 12
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 650
type_name:
  max_length: 
    warning: 40
    error: 50
identifier_name:
  excluded:
    - id
    - on

disabled_rules: # 执行时排除掉的规则
  - multiple_closures_with_trailing_closure
    
